MY_CODE = "jackofdimonds"

action:
	@echo $(MY_CODE)

run: Calculator.exe
	Calculator.exe $(MY_CODE)

Calculator.exe: Calculator.cpp
	g++ Calculator.cpp Text_processing.cpp -o Calculator.exe

run_asm: Assembler.exe
	Assembler.exe $(MY_CODE)

Assembler.exe: $(MY_CODE) CPU_header.h Assembler.cpp Text_processing.cpp
	g++ Assembler.cpp Text_processing.cpp -o Assembler.exe

